/* ====================================================
   Reader — Book Catalog
   50 classics from Project Gutenberg, ordered by
   cultural significance and reading variety.
   ==================================================== */

const GENRE_PALETTE = {
  'Romance':    { bg: '#C17A8A', text: '#fff' },
  'Horror':     { bg: '#7B5EA7', text: '#fff' },
  'Mystery':    { bg: '#4A7FA5', text: '#fff' },
  'Adventure':  { bg: '#3D9B7A', text: '#fff' },
  'Sci-Fi':     { bg: '#3A7CC4', text: '#fff' },
  'Drama':      { bg: '#B07840', text: '#fff' },
  'Comedy':     { bg: '#C4A020', text: '#fff' },
  'Philosophy': { bg: '#5A8C6A', text: '#fff' },
  'Fantasy':    { bg: '#8B62C4', text: '#fff' },
  'Fiction':    { bg: '#A05878', text: '#fff' },
  'Historical': { bg: '#8C6040', text: '#fff' },
  'Epic':       { bg: '#405898', text: '#fff' },
  'Non-Fiction':{ bg: '#4A9480', text: '#fff' },
  'Fables':     { bg: '#8A9030', text: '#fff' },
};

// Returns {bg, text} for a genre, with slight per-book variation
function getBookColors(genre, index) {
  const base = GENRE_PALETTE[genre] || { bg: '#6B5EA8', text: '#fff' };
  // Darken/lighten slightly based on index for variety within genre
  return base;
}

// Project Gutenberg URL patterns (tried in order)
function gutenbergUrls(id) {
  return [
    `https://www.gutenberg.org/cache/epub/${id}/pg${id}.txt`,
    `https://www.gutenberg.org/files/${id}/${id}-0.txt`,
    `https://www.gutenberg.org/files/${id}/${id}.txt`,
  ];
}

const BOOKS = [
  {
    id: 1342,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    genre: "Romance",
    desc: "The witty Elizabeth Bennet navigates love, class, and first impressions in Regency England.",
  },
  {
    id: 84,
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    genre: "Horror",
    desc: "A scientist creates life but cannot face responsibility for his monstrous creation.",
  },
  {
    id: 1661,
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    year: 1892,
    genre: "Mystery",
    desc: "Twelve classic detective stories featuring the brilliant, eccentric Sherlock Holmes.",
  },
  {
    id: 11,
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    year: 1865,
    genre: "Fantasy",
    desc: "A girl falls into a rabbit hole and enters a world of delightful, surreal nonsense.",
  },
  {
    id: 5200,
    title: "The Metamorphosis",
    author: "Franz Kafka",
    year: 1915,
    genre: "Fiction",
    desc: "A traveling salesman wakes one morning to find himself transformed into a giant insect.",
  },
  {
    id: 2701,
    title: "Moby-Dick",
    author: "Herman Melville",
    year: 1851,
    genre: "Adventure",
    desc: "Captain Ahab's obsessive, all-consuming quest to hunt the legendary white whale.",
  },
  {
    id: 98,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    year: 1859,
    genre: "Historical",
    desc: "A story of sacrifice and redemption set against the backdrop of the French Revolution.",
  },
  {
    id: 844,
    title: "The Importance of Being Earnest",
    author: "Oscar Wilde",
    year: 1895,
    genre: "Comedy",
    desc: "A trivial comedy for serious people, sparkling with wit and incisive social satire.",
  },
  {
    id: 174,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    genre: "Horror",
    desc: "A portrait bears the scars of sin while its beautiful subject stays eternally young.",
  },
  {
    id: 345,
    title: "Dracula",
    author: "Bram Stoker",
    year: 1897,
    genre: "Horror",
    desc: "Jonathan Harker's journey to Transylvania begins a terrifying battle with an immortal vampire.",
  },
  {
    id: 2554,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    genre: "Fiction",
    desc: "A student commits murder and is consumed by guilt, paranoia, and moral disintegration.",
  },
  {
    id: 43,
    title: "Dr Jekyll and Mr Hyde",
    author: "Robert Louis Stevenson",
    year: 1886,
    genre: "Horror",
    desc: "A scientist's experiments unleash the darkest side of human nature.",
  },
  {
    id: 120,
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    year: 1883,
    genre: "Adventure",
    desc: "Young Jim Hawkins sets sail for buried treasure with treacherous pirates on his trail.",
  },
  {
    id: 36,
    title: "The War of the Worlds",
    author: "H.G. Wells",
    year: 1898,
    genre: "Sci-Fi",
    desc: "Martians invade Earth with devastating war machines, threatening all of civilization.",
  },
  {
    id: 1513,
    title: "Romeo and Juliet",
    author: "William Shakespeare",
    year: 1597,
    genre: "Drama",
    desc: "Two young lovers from feuding families are torn apart by fate in Verona.",
  },
  {
    id: 1524,
    title: "Hamlet",
    author: "William Shakespeare",
    year: 1603,
    genre: "Drama",
    desc: "The Prince of Denmark seeks revenge for his father's murder while consumed by doubt.",
  },
  {
    id: 1533,
    title: "Macbeth",
    author: "William Shakespeare",
    year: 1606,
    genre: "Drama",
    desc: "Prophecy and ambition drive a Scottish general to murder, madness, and ruin.",
  },
  {
    id: 1514,
    title: "A Midsummer Night's Dream",
    author: "William Shakespeare",
    year: 1600,
    genre: "Comedy",
    desc: "Lovers, fairies, and bumbling players weave magical confusion in an enchanted forest.",
  },
  {
    id: 74,
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    year: 1876,
    genre: "Adventure",
    desc: "A mischievous boy's adventures and misadventures along the great Mississippi River.",
  },
  {
    id: 76,
    title: "Adventures of Huckleberry Finn",
    author: "Mark Twain",
    year: 1884,
    genre: "Adventure",
    desc: "Huck and Jim journey down the Mississippi, seeking freedom and discovering America.",
  },
  {
    id: 1184,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    year: 1844,
    genre: "Adventure",
    desc: "An unjustly imprisoned man escapes and returns to exact an elaborate, patient revenge.",
  },
  {
    id: 1257,
    title: "The Three Musketeers",
    author: "Alexandre Dumas",
    year: 1844,
    genre: "Adventure",
    desc: "D'Artagnan joins Athos, Porthos, and Aramis to defend honor and serve the king.",
  },
  {
    id: 103,
    title: "Around the World in 80 Days",
    author: "Jules Verne",
    year: 1872,
    genre: "Adventure",
    desc: "The eccentric Phileas Fogg bets his fortune he can circumnavigate the globe in 80 days.",
  },
  {
    id: 164,
    title: "Twenty Thousand Leagues Under the Sea",
    author: "Jules Verne",
    year: 1870,
    genre: "Sci-Fi",
    desc: "Explorers become prisoners aboard Captain Nemo's astonishing submarine, the Nautilus.",
  },
  {
    id: 3748,
    title: "Journey to the Center of the Earth",
    author: "Jules Verne",
    year: 1864,
    genre: "Sci-Fi",
    desc: "A professor leads his nephew into an Icelandic volcano toward the very core of the Earth.",
  },
  {
    id: 35,
    title: "The Time Machine",
    author: "H.G. Wells",
    year: 1895,
    genre: "Sci-Fi",
    desc: "A Victorian inventor travels far into the future to discover the fate of humanity.",
  },
  {
    id: 5230,
    title: "The Invisible Man",
    author: "H.G. Wells",
    year: 1897,
    genre: "Sci-Fi",
    desc: "A scientist discovers the secret of invisibility, then descends into isolation and madness.",
  },
  {
    id: 2097,
    title: "The Island of Doctor Moreau",
    author: "H.G. Wells",
    year: 1896,
    genre: "Sci-Fi",
    desc: "A shipwrecked man discovers an island where a scientist creates terrible human-animal hybrids.",
  },
  {
    id: 215,
    title: "The Call of the Wild",
    author: "Jack London",
    year: 1903,
    genre: "Adventure",
    desc: "A domesticated dog is thrust into the brutal Klondike wilderness and must find his wild self.",
  },
  {
    id: 910,
    title: "White Fang",
    author: "Jack London",
    year: 1906,
    genre: "Adventure",
    desc: "A wolf-dog raised in the harsh Yukon wilderness learns to trust and love in a human world.",
  },
  {
    id: 161,
    title: "Sense and Sensibility",
    author: "Jane Austen",
    year: 1811,
    genre: "Romance",
    desc: "Two sisters with opposing natures navigate love, heartbreak, and social expectations.",
  },
  {
    id: 158,
    title: "Emma",
    author: "Jane Austen",
    year: 1815,
    genre: "Romance",
    desc: "A charming, well-meaning young woman plays matchmaker with entertaining unintended consequences.",
  },
  {
    id: 1260,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    year: 1847,
    genre: "Romance",
    desc: "An orphaned governess finds love and independence against Victorian social constraints.",
  },
  {
    id: 768,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    year: 1847,
    genre: "Romance",
    desc: "A passionate, destructive love story set on the wild and desolate Yorkshire moors.",
  },
  {
    id: 514,
    title: "Little Women",
    author: "Louisa May Alcott",
    year: 1868,
    genre: "Fiction",
    desc: "The four March sisters grow up during the Civil War, each pursuing her own dreams.",
  },
  {
    id: 4300,
    title: "Ulysses",
    author: "James Joyce",
    year: 1922,
    genre: "Fiction",
    desc: "A single day in Dublin through the stream-of-consciousness of Leopold Bloom, mirroring The Odyssey.",
  },
  {
    id: 996,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    year: 1605,
    genre: "Fiction",
    desc: "A man so consumed by tales of chivalry that he sets out as a knight-errant to right all wrongs.",
  },
  {
    id: 135,
    title: "Les Misérables",
    author: "Victor Hugo",
    year: 1862,
    genre: "Historical",
    desc: "Jean Valjean's decades-long pursuit of redemption in the shadow of revolution and the relentless Javert.",
  },
  {
    id: 2600,
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: 1869,
    genre: "Historical",
    desc: "A sweeping portrait of Russian society and five aristocratic families during the Napoleonic Wars.",
  },
  {
    id: 1399,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    year: 1878,
    genre: "Fiction",
    desc: "A married aristocrat risks everything for a passionate affair that society will not forgive.",
  },
  {
    id: 28054,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    genre: "Fiction",
    desc: "Three brothers, a murdered father, and searching questions of faith, doubt, and morality.",
  },
  {
    id: 600,
    title: "Notes from Underground",
    author: "Fyodor Dostoevsky",
    year: 1864,
    genre: "Fiction",
    desc: "A bitter, hyper-aware civil servant rails against society and reason from his underground existence.",
  },
  {
    id: 1727,
    title: "The Odyssey",
    author: "Homer",
    year: -800,
    genre: "Epic",
    desc: "Odysseus's epic ten-year journey home from Troy, facing monsters, gods, and terrible temptation.",
  },
  {
    id: 6130,
    title: "The Iliad",
    author: "Homer",
    year: -762,
    genre: "Epic",
    desc: "The wrath of Achilles and the siege of Troy in the greatest war epic of the ancient world.",
  },
  {
    id: 1497,
    title: "The Republic",
    author: "Plato",
    year: -380,
    genre: "Philosophy",
    desc: "Socratic dialogues exploring justice, the nature of the ideal state, and the philosopher-king.",
  },
  {
    id: 2680,
    title: "Meditations",
    author: "Marcus Aurelius",
    year: 180,
    genre: "Philosophy",
    desc: "Private reflections of a Roman emperor — a timeless guide to Stoic philosophy and virtuous living.",
  },
  {
    id: 205,
    title: "Walden",
    author: "Henry David Thoreau",
    year: 1854,
    genre: "Non-Fiction",
    desc: "Two years living simply in the Massachusetts woods — a meditation on nature and self-reliance.",
  },
  {
    id: 132,
    title: "The Art of War",
    author: "Sun Tzu",
    year: -500,
    genre: "Philosophy",
    desc: "Ancient Chinese military strategy with timeless wisdom on conflict, leadership, and deception.",
  },
  {
    id: 2591,
    title: "Grimm's Fairy Tales",
    author: "Brothers Grimm",
    year: 1812,
    genre: "Fantasy",
    desc: "Beloved folk tales from Cinderella to Rumpelstiltskin, collected by Jacob and Wilhelm Grimm.",
  },
  {
    id: 11339,
    title: "Aesop's Fables",
    author: "Aesop",
    year: -620,
    genre: "Fables",
    desc: "Timeless moral tales featuring animals whose follies perfectly mirror the weaknesses of human nature.",
  },
  {
    id: 2852,
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    year: 1902,
    genre: "Mystery",
    desc: "Holmes and Watson investigate a supernatural hound terrorizing the Baskerville family on the moors.",
  },
];

// Attach colors to each book
BOOKS.forEach((book, i) => {
  book.colors = getBookColors(book.genre, i);
});

// Formatted display year (handles BC)
function formatYear(year) {
  if (year === undefined || year === null) return '';
  return year < 0 ? `${Math.abs(year)} BC` : String(year);
}
