/* Read Free — service worker. GENERATED by scripts/build.mjs from scripts/sw.template.js; do not edit sw.js. */

const VERSION = '2.0.0+89dca36604'
const CACHE = `reader-shell-${VERSION}`
const PRECACHE = [
  "./",
  "./index.html",
  "./manifest.json",
  "./app/audio/chapters.js",
  "./app/audio/librivox.js",
  "./app/audio/read-along.js",
  "./app/audio/sync.js",
  "./app/boot-theme.js",
  "./app/catalog/gutenberg.js",
  "./app/catalog/opds.js",
  "./app/catalog/standard-ebooks.js",
  "./app/db.js",
  "./app/library.js",
  "./app/main.js",
  "./app/net.js",
  "./app/reader/autopilot.js",
  "./app/reader/define.js",
  "./app/reader/footnotes.js",
  "./app/reader/highlights.js",
  "./app/reader/reader.js",
  "./app/reader/rsvp.js",
  "./app/reader/tts.js",
  "./app/settings.js",
  "./app/share/quote-image.js",
  "./app/share/quote-link.js",
  "./app/share/share-sheet.js",
  "./app/stats.js",
  "./app/sw-client.js",
  "./app/txt/gutenberg.js",
  "./app/txt/txt-book.js",
  "./app/ui/covers.js",
  "./app/ui/discover.js",
  "./app/ui/dom.js",
  "./app/ui/install.js",
  "./app/ui/settings-screen.js",
  "./app/ui/type-sheet.js",
  "./app/version.js",
  "./styles/app.css",
  "./styles/fonts.css",
  "./fonts/atkinson-hyperlegible-latin-400-italic.woff2",
  "./fonts/atkinson-hyperlegible-latin-400-normal.woff2",
  "./fonts/atkinson-hyperlegible-latin-700-italic.woff2",
  "./fonts/atkinson-hyperlegible-latin-700-normal.woff2",
  "./fonts/literata-latin-ext-wght-italic.woff2",
  "./fonts/literata-latin-ext-wght-normal.woff2",
  "./fonts/literata-latin-wght-italic.woff2",
  "./fonts/literata-latin-wght-normal.woff2",
  "./fonts/opendyslexic-latin-400-italic.woff2",
  "./fonts/opendyslexic-latin-400-normal.woff2",
  "./fonts/opendyslexic-latin-700-normal.woff2",
  "./vendor/foliate-js/comic-book.js",
  "./vendor/foliate-js/dict.js",
  "./vendor/foliate-js/epub.js",
  "./vendor/foliate-js/epubcfi.js",
  "./vendor/foliate-js/fb2.js",
  "./vendor/foliate-js/fixed-layout.js",
  "./vendor/foliate-js/footnotes.js",
  "./vendor/foliate-js/mobi.js",
  "./vendor/foliate-js/opds.js",
  "./vendor/foliate-js/overlayer.js",
  "./vendor/foliate-js/paginator.js",
  "./vendor/foliate-js/progress.js",
  "./vendor/foliate-js/search.js",
  "./vendor/foliate-js/text-walker.js",
  "./vendor/foliate-js/tts.js",
  "./vendor/foliate-js/uri-template.js",
  "./vendor/foliate-js/vendor/fflate.js",
  "./vendor/foliate-js/vendor/zip.js",
  "./vendor/foliate-js/view.js",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon.svg",
  "./icons/maskable-512.png",
  "./data/starter.json"
]

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    // cache: 'reload' bypasses the HTTP cache so a new version never mixes in stale files
    await cache.addAll(PRECACHE.map(url => new Request(url, { cache: 'reload' })))
  })())
  // First install activates immediately; updates wait for the user to accept (see sw-client.js).
  // The legacy 1.x worker ("reader-vN" caches) has no update prompt, so replace it right away.
  event.waitUntil((async () => {
    const legacy = (await caches.keys()).some(k => /^reader-v\d+$/.test(k))
    if (!self.registration.active || legacy) await self.skipWaiting()
  })())
})

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys()
    await Promise.all(keys.filter(k => k.startsWith('reader-') && k !== CACHE && k !== 'reader-share').map(k => caches.delete(k)))
    await self.clients.claim()
  })())
})

self.addEventListener('message', event => {
  if (event.data === 'skip-waiting') self.skipWaiting()
})

self.addEventListener('fetch', event => {
  const { request } = event
  const url = new URL(request.url)

  // Web Share Target (Android): stash shared files, then let the app import them.
  if (request.method === 'POST' && url.pathname.endsWith('/share-target')) {
    event.respondWith((async () => {
      const form = await request.formData()
      const cache = await caches.open('reader-share')
      for (const file of form.getAll('books')) {
        if (!(file instanceof File)) continue
        await cache.put(`./shared/${Date.now()}-${encodeURIComponent(file.name)}`,
          new Response(file, { headers: { 'Content-Type': file.type || 'application/octet-stream', 'X-File-Name': encodeURIComponent(file.name) } }))
      }
      return Response.redirect('./#/library?shared=1', 303)
    })())
    return
  }

  if (request.method !== 'GET') return
  if (url.origin !== self.location.origin) return // libraries are fetched directly by the app

  if (request.mode === 'navigate') {
    const scope = new URL(self.registration.scope)
    const rest = url.pathname.slice(scope.pathname.length)
    // Shared quote links (readfree.app/q/…) open straight in the app, even offline.
    if (rest.startsWith('q/')) {
      event.respondWith(Response.redirect(new URL(`#/q/${rest.slice(2)}${url.search}`, scope).href, 302))
      return
    }
    // Other server paths (preview images, oEmbed) aren't the app.
    if (rest && rest !== 'index.html') return
    // App navigations get the cached shell (the app routes with #hash).
    event.respondWith((async () => {
      const cached = await caches.match('./index.html', { cacheName: CACHE })
      if (cached) return cached
      return fetch(request)
    })())
    return
  }

  // Starter-shelf book files are stored in IndexedDB by the app; never cache them twice.
  if (url.pathname.includes('/books/')) return

  event.respondWith((async () => {
    const cached = await caches.match(request, { cacheName: CACHE, ignoreSearch: true })
    if (cached) return cached
    return fetch(request)
  })())
})
