/* Read Free — service worker. GENERATED by scripts/build.mjs from scripts/sw.template.js; do not edit sw.js. */

const VERSION = '2.0.0+36f1c87896'
const CACHE = `reader-shell-${VERSION}`
const PRECACHE = {
  "./": "595a5db0a96d78c2de4c59ca2802e66df848ab4f8bd9e8f4236f35912d332df9",
  "./index.html": "595a5db0a96d78c2de4c59ca2802e66df848ab4f8bd9e8f4236f35912d332df9",
  "./manifest.json": "da18f0b0ccdde93c95076194bce614d578eec8b45698ae9648068fa9dcce5302",
  "./app/audio/chapters.js": "52a7e80362b7fdc85d56c416fa07d42c7ecb0d738bad6189b44c9ffba07a44f8",
  "./app/audio/librivox.js": "ddafa88ddd5d2f00fdf2c324c92a6ec51bff2262bcc0dbc7e839366bd0132ff8",
  "./app/audio/read-along.js": "1c05a7f211d10ca0bdbb275f5d1da4763d0458debe58e3b050942509cc4e109c",
  "./app/audio/sync.js": "9ec4a4b22fce0699e948316db0eb80c018671470299054c9b42183730114380f",
  "./app/boot-theme.js": "d545c74e2a6ba52250c47c89c36da3392abf613fb21cc87c33ad8b1174c30553",
  "./app/catalog/gutenberg.js": "b26875f360018a59d5031591bd32529758c3c3c9d2771c80ad5a0187df127325",
  "./app/catalog/opds.js": "4d0ff516e929655520d4be95f5cd38a9d7f3b4f7a43e855b4d32cb87a2aa16d8",
  "./app/catalog/standard-ebooks.js": "3b2d2f4a4494c3f6a242fa314b48ba79335d2dba7e5df5f9d69e47261b25edc0",
  "./app/db.js": "3a5f596db383d00895d7dc4860ed8ae1f0a10d7dd607c80afa6542a90e83dbd6",
  "./app/library.js": "da8d5d94020da75fa1969c8418fc8788c52418ba7e6a6276ced118f1e4b181a0",
  "./app/main.js": "eb41162f6d69edcd20008521a742782d52a403e822768c6ed5a0ca9e5c458cc3",
  "./app/net.js": "cad1e5abad21856a1e3f5e68f7dbf5a23b971fd1822dcef027b2f61dea1851e6",
  "./app/reader/autopilot.js": "c00ca5ff0c516f3fa54913ab8ee7caf0c04655791c720c4be9b2c6f1b3cf3c58",
  "./app/reader/define.js": "6110dae365b5c19d9abbf5300f4f58be9144bc60343de2132017eed75051e902",
  "./app/reader/footnotes.js": "4400016ed043cf9e59c2633db78c7bf4306bdd265e1274f4e0ecd8ff91725431",
  "./app/reader/highlights.js": "b1230ea28341e4187fb6de1ea94eb2ee2bfb864234fde2486f65ef761e3deddd",
  "./app/reader/reader.js": "814c8b7c376ac0d1178f1ba506de2ff917fbc4b9b29116e238b91696dd4250e1",
  "./app/reader/rsvp.js": "484be9f9f1e757d37b70398f9927ee569caacee4a7347f2f907be5529c4ccb9b",
  "./app/reader/tts.js": "63ecf91cce39e1696ef9d1f075b01d41ac76754086cd8081eaa7fe7ba2792d7c",
  "./app/settings.js": "aa0a2633b61a8e5dd9145dc0eece7d33baf362bab6ca8c131c5ad138a4e57c77",
  "./app/share/quote-image.js": "26215d723679c91fb600fc96e1deb2e817ee8f669518b91c094f95f8bc141811",
  "./app/share/quote-link.js": "2bf80fefc507a72f628e886754bc00349a54ed9cfc76b105c52b705736106326",
  "./app/share/share-sheet.js": "6627fbb393e271d2ab36287a3498e64bb1b4fcaa4f41b0598af028e7fa5da259",
  "./app/stats.js": "f4a7c2e8b3f1ac7f57e2e23efecd585e56008199701897249bf189ec59b549ef",
  "./app/sw-client.js": "23496920df0ffac2adaaf0153efeee79db9d80421c08a54df8f832a18d68dcfa",
  "./app/txt/gutenberg.js": "4a1f73e596e221bfccff71575ebce83d8c99e1bde07b34640027cb3f7715ebb9",
  "./app/txt/txt-book.js": "4e5c8674a2527e99517c61052790a592fa934ca8d2259fdc6a5a18bead917ac7",
  "./app/ui/covers.js": "76a59b6d780290065ef08d8f11e3e0f8710caebf32c2aa09f66b674469b3e51c",
  "./app/ui/discover.js": "1a8f58f8813c0ba020bb69b6b54283be5b7141b531682f1cb9fc0ca8aa12529c",
  "./app/ui/dom.js": "b1b0a3b74ae9b57debf77d431783da3367e556323fb82df7581647d61ecbf2a4",
  "./app/ui/install.js": "b0a54b419fa0cf0f1790c6248334bf538fab36c3f855344f43ce8e7932869e4c",
  "./app/ui/settings-screen.js": "707f7695b53c289a56f5f41b1dc7ea6b247a6b17224662ac01d611b12f3067de",
  "./app/ui/type-sheet.js": "9c039b99762351959a077974f46dc8601f912ac62b9a018b63b585b792acfc95",
  "./app/version.js": "bf722c236e76bb431174f86d6a98ce816b9f123d770160b32c3a928ade1ec28e",
  "./styles/app.css": "56d45f3ecf6baa2ef5e216112683b498984afe6a1103001215ffb3dbfc389e20",
  "./styles/fonts.css": "a4602039220b04d696b565eddaaff54d8ad0197c7ce068ac2823df536c4636e2",
  "./fonts/atkinson-hyperlegible-latin-400-italic.woff2": "bc8825fd435d4aa8e31449937826d583a7daaae15a83832c91b38375131ebf08",
  "./fonts/atkinson-hyperlegible-latin-400-normal.woff2": "d64ba838ef5472bba248620ec4fd8b5aa7cf0db2908e0bb230600caf279ba7bc",
  "./fonts/atkinson-hyperlegible-latin-700-italic.woff2": "73e0c9e1e284128dda599558f7c15bd5f3c056442c31dfae950528a16b3835cf",
  "./fonts/atkinson-hyperlegible-latin-700-normal.woff2": "140e2bd25a7315c8a062508391426b0d8c3297400c947b8d847be28f73a199f0",
  "./fonts/literata-latin-ext-wght-italic.woff2": "ba0e6a12e2f0a1f5d455c23c47068b71f9898c571dcb92dab385294ebdae3e74",
  "./fonts/literata-latin-ext-wght-normal.woff2": "46792f7cd10b28fb512161caeaaa11b049feb2221ccaa72bb4d4ccc286199155",
  "./fonts/literata-latin-wght-italic.woff2": "ab198d6616c7cc966f26a4a5b28a3977dc47439640f09d9b3361226bd465c404",
  "./fonts/literata-latin-wght-normal.woff2": "9adbeac5b167fe5ad6c49d9e29aa0c76e2f1bb3b46bf4ebf12a9eca7d3525384",
  "./fonts/opendyslexic-latin-400-italic.woff2": "eb6a1bacf7e7c87a08116af4cd00a82064fbe61647b9a0d4d70a339890268f88",
  "./fonts/opendyslexic-latin-400-normal.woff2": "f007004af3cda5d8076e57c943f8cc8d00a0da25988b1ae1048683d60e7cac1a",
  "./fonts/opendyslexic-latin-700-normal.woff2": "dd9fa9c7991113b0dddefe9506a30ad26b48e302b7a8fb91719a4726e8fde85b",
  "./vendor/foliate-js/comic-book.js": "7f3bf77561ca77300d5244015fcb1f73805787db246928074dc49fb56c88762e",
  "./vendor/foliate-js/dict.js": "9c5f7d9d87ebec302594178f8960539a4573830f9ef84c8a915f599047dcc4aa",
  "./vendor/foliate-js/epub.js": "dfe347495039e9b5991478986ec6b7713cf9efbcd8f475a77ef7b967c5176298",
  "./vendor/foliate-js/epubcfi.js": "e1a688ad5c84bf31f33cef467f92c7a6d060a0f17ec37c1d3c048e9c7b1cf645",
  "./vendor/foliate-js/fb2.js": "09a7890bf191f1b6c6dd435fae2868b86c75e73e00731b0051c02f2a998a180a",
  "./vendor/foliate-js/fixed-layout.js": "7aee1d15d8e0479b8a6c59a20304b250dafc4c7dc158147a2b2c6bed9e180b4c",
  "./vendor/foliate-js/footnotes.js": "d377b45d2ac05290c42873612ec0a92e640938e8be8ed850a467133a883388de",
  "./vendor/foliate-js/mobi.js": "016526df13a9f11ee6671a8c74346e1cf41fe6bdfe50165fdcbf744f015694f3",
  "./vendor/foliate-js/opds.js": "4b9f2a8f77ba191e1bb892032fd21a4e2ca14e5ff0b14239421d331556fa352f",
  "./vendor/foliate-js/overlayer.js": "d3d3396e3083277ccbd4f17c407621159b22a407107e43ce75ca3014578094fb",
  "./vendor/foliate-js/paginator.js": "8b8dd39a89239949ba8fb18d0f126520fd1f6349128b84f841ca10ff842521a5",
  "./vendor/foliate-js/progress.js": "544f5e90babc0cb31c5caf971a5f06dd6249ec06600cb62f672fa7179811fde1",
  "./vendor/foliate-js/search.js": "31e846bdc095a645de0e94f7baa2c9e136561a363a2f774d4032e72cfa1fb0ef",
  "./vendor/foliate-js/text-walker.js": "4ad740ab6142b5be428700ef4d270253cef6649cf6e047ae7d2698a7aec65e92",
  "./vendor/foliate-js/tts.js": "530d34605b758a5e2260438964a85bb9909bcb49e8848e303fe22cac63859026",
  "./vendor/foliate-js/uri-template.js": "28bd96a9960cbfb07e14d4b9e9f334f28d1c3c96cbd8d58880631dcb1387e9f6",
  "./vendor/foliate-js/vendor/fflate.js": "e63bcc21f83a43e5f71d5cbefd351ff4d4dbd57bef8b29ad65c8bd65752f6e6b",
  "./vendor/foliate-js/vendor/zip.js": "2a0d43157e4a447c6e43351225758795b75a33e8dfec10c6767248df2182949a",
  "./vendor/foliate-js/view.js": "e0093af921feb03bb58fb51aeedc321fa108a4158d215f6913ecf7925415c945",
  "./icons/apple-touch-icon.png": "a5fd81144bcbd9eb99038ebdd3dce5c542f02596df603f51da7efafe6ca3c938",
  "./icons/icon-192.png": "c96b3adb9af18914f96b8fb93e69fc6b1a4b44388f7ce724364bdc4f1f4eef8d",
  "./icons/icon-512.png": "90a469b1d73ddde8d0f722540d2cb41f9360e7b388860d31c05f462c83f04a42",
  "./icons/icon.svg": "1c5b33dfaffaca8e91e6ea734445e843f26db5aaecb328d94e350c520bb0ddd5",
  "./icons/maskable-512.png": "830b76c9bbcf8b9cbe841d5a255968c14bf17e958ec592b09f0ef824d8d7fb63",
  "./data/starter.json": "909bcc6c31faac8415749f907238f311cfe611b04aa42626a87a1064b7baef1c"
} // { url: sha256 }

const hex = buf => [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('')

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    // cache: 'reload' bypasses the HTTP cache, and every file must match this
    // version's fingerprint. Right after a deploy a CDN can still hand out some
    // old files; then this update fails, the current version keeps working, and
    // the browser tries again later.
    const files = await Promise.all(Object.entries(PRECACHE).map(async ([url, expected]) => {
      const request = new Request(url, { cache: 'reload' })
      const response = await fetch(request)
      if (!response.ok) throw new Error(`${url}: ${response.status}`)
      const actual = hex(await crypto.subtle.digest('SHA-256', await response.clone().arrayBuffer()))
      if (actual !== expected) throw new Error(`${url} is from a different version`)
      return [request, response]
    }))
    const cache = await caches.open(CACHE)
    await Promise.all(files.map(([request, response]) => cache.put(request, response)))
  })())
  // First install activates immediately; updates wait for the user to accept (see sw-client.js).
  // The legacy 1.x worker ("reader-vN" caches) has no update prompt, so replace it right away.
  event.waitUntil((async () => {
    const legacy = (await caches.keys()).some(k => /^reader-v\d+$/.test(k))
    if (!self.registration.active || legacy) await self.skipWaiting()
  })())
})

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys()
    await Promise.all(keys.filter(k => k.startsWith('reader-') && k !== CACHE && k !== 'reader-share').map(k => caches.delete(k)))
    await self.clients.claim()
  })())
})

self.addEventListener('message', event => {
  if (event.data === 'skip-waiting') self.skipWaiting()
})

self.addEventListener('fetch', event => {
  const { request } = event
  const url = new URL(request.url)

  // Web Share Target (Android): stash shared files, then let the app import them.
  if (request.method === 'POST' && url.pathname.endsWith('/share-target')) {
    event.respondWith((async () => {
      const form = await request.formData()
      const cache = await caches.open('reader-share')
      for (const file of form.getAll('books')) {
        if (!(file instanceof File)) continue
        await cache.put(`./shared/${Date.now()}-${encodeURIComponent(file.name)}`,
          new Response(file, { headers: { 'Content-Type': file.type || 'application/octet-stream', 'X-File-Name': encodeURIComponent(file.name) } }))
      }
      return Response.redirect('./#/library?shared=1', 303)
    })())
    return
  }

  if (request.method !== 'GET') return
  if (url.origin !== self.location.origin) return // libraries are fetched directly by the app

  if (request.mode === 'navigate') {
    const scope = new URL(self.registration.scope)
    const rest = url.pathname.slice(scope.pathname.length)
    // Shared quote links (readfree.app/q/…) open straight in the app, even offline.
    if (rest.startsWith('q/')) {
      event.respondWith(Response.redirect(new URL(`#/q/${rest.slice(2)}${url.search}`, scope).href, 302))
      return
    }
    // Other server paths (preview images, oEmbed) aren't the app.
    if (rest && rest !== 'index.html') return
    // App navigations get the cached shell (the app routes with #hash).
    event.respondWith((async () => {
      const cached = await caches.match('./index.html', { cacheName: CACHE })
      if (cached) return cached
      return fetch(request)
    })())
    return
  }

  // Starter-shelf book files are stored in IndexedDB by the app; never cache them twice.
  if (url.pathname.includes('/books/')) return

  event.respondWith((async () => {
    const cached = await caches.match(request, { cacheName: CACHE, ignoreSearch: true })
    if (cached) return cached
    return fetch(request)
  })())
})
