#!/usr/bin/env node
/* Generates sw.js (precache list + content hash) and app/version.js.
 *   node scripts/build.mjs          write files
 *   node scripts/build.mjs --check  fail if generated files are stale (CI) */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const check = process.argv.includes('--check')

const walk = dir => readdirSync(join(root, dir)).flatMap(name => {
  const rel = join(dir, name)
  return statSync(join(root, rel)).isDirectory() ? walk(rel) : [rel]
})

const include = [
  'index.html', 'manifest.json',
  ...walk('app').filter(f => f.endsWith('.js') && f !== 'app/version.js'),
  'app/version.js',
  ...walk('styles').filter(f => f.endsWith('.css')),
  ...walk('fonts').filter(f => f.endsWith('.woff2')),
  ...walk('vendor/foliate-js').filter(f => f.endsWith('.js')),
  ...walk('icons').filter(f => /\.(png|svg)$/.test(f)),
  'data/starter.json',
]

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const hash = createHash('sha256')
for (const f of include.filter(f => f !== 'app/version.js').sort()) {
  hash.update(f)
  hash.update(readFileSync(join(root, f)))
}
const digest = hash.digest('hex').slice(0, 10)
const version = `${pkg.version}+${digest}`

const versionJs = `// GENERATED by scripts/build.mjs\nexport const APP_VERSION = '${version}'\n`
// Each precached file with its SHA-256, so the service worker can refuse a
// half-deployed mix of old and new files (CDNs can serve both for a while).
const sha = buf => createHash('sha256').update(buf).digest('hex')
const precache = { './': sha(readFileSync(join(root, 'index.html'))) }
for (const f of include) precache[`./${f}`] = sha(f === 'app/version.js' ? versionJs : readFileSync(join(root, f)))

const outputs = {
  'app/version.js': versionJs,
  'sw.js': readFileSync(join(root, 'scripts/sw.template.js'), 'utf8')
    .replace('__VERSION__', version)
    .replace('__PRECACHE__', JSON.stringify(precache, null, 2)),
}

let stale = []
for (const [file, content] of Object.entries(outputs)) {
  const path = join(root, file)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : ''
  if (current === content) continue
  if (check) stale.push(file)
  else writeFileSync(path, content)
}
if (check && stale.length) {
  console.error(`Generated files are stale: ${stale.join(', ')}. Run: npm run build`)
  process.exit(1)
}
console.log(`${check ? 'checked' : 'built'} ${version} (${include.length} precached files)`)
